### ISSUE TITLE
【代码问题】logging包写入日志的文件

### ISSUE THREAD

**Issue by cugxuan** [EDDYCJY/blog#16]
如果跨天的话，就不会写到第二天的文件里面去。因为这个日期是在setup（或者是init函数中设置的）
![image](https://user-images.githubusercontent.com/23120372/50828060-415c8b80-137b-11e9-8948-c878a02309c5.png)

如果要修改的话大概用什么方案？

**Comment by cugxuan** [comment]
每次写log的时候都查一次时间会不会太消耗性能了。

**Comment by EDDYCJY** [comment]
@cugxuan 感谢反馈，你反馈的跨天写入日志文件的问题，的确可以通过每次写入日志的时候，去查询时间来实现这个功能点

但是会对性能有一定损耗。但是要分场景了，绝大部分 Web 应用不会受这种小幅度损耗影响的。因为瓶颈压根不在此

而如果是更实际的话。结合 @solarhell 给你的意见。其实在我们生产环境上的日志，都是可以存放到一个日志文件里的（不按日期）切割文件。因为我们最后的日志分类和字段展示都是通过 “日志平台” 来进行自动管理和切割的。不会由应用层去处理

如果是要我这边修改的话，我会更偏向于把它改为一个文件存放的方案。目前的主流趋势，就是应用存放单文件即可，其余由自动化脚本和日志平台分析捕抓和清理冗余日志即可

**Comment by cugxuan** [comment]
@solarhell @EDDYCJY 感谢大佬们、大致了解了。之后我再去了解一下常用的解决方案。

**Comment by EDDYCJY** [comment]
@cugxuan 不客气，如果有问题欢迎再讨论。我说的方案基本是业界常见了。如果你想以最快的了解，顺便搞一搞（实操一波）的话，建议 ELK 走一遭
