### ISSUE TITLE
关于swagger

### ISSUE THREAD

**Issue by xiaoguiSniper** [EDDYCJY/blog#19]
作者你好，关于swagger，我在写post请求的时候，想定义入参为数组类型。
```
type X struct {
IDs []int64
}
```
大概想这么写，在@Param里面类型写的body，但是得不到正确的输出，请问有什么解决方案吗

**Comment by EDDYCJY** [comment]
这个不难，你可以参考 gin-swagger 的 examples，传送门：https://github.com/swaggo/gin-swagger/blob/master/example/api/api.go#L16

简单来讲，就是定义 object 类型引用指定 struct 类型就可以了
