### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Devying** [EDDYCJY/blog#2]
[redis协议](https://github.com/EDDYCJY/blog/blob/master/golang/2018-06-07-%E7%94%A8Go%E6%9D%A5%E4%BA%86%E8%A7%A3%E4%B8%80%E4%B8%8BRedis%E9%80%9A%E8%AE%AF%E5%8D%8F%E8%AE%AE.md)
```
// 读取回复
	command := make([]byte, 1024)
	n, err := redisConn.Read(command)
	if err != nil {
		log.Fatalf("Conn Read err: %v", err)
	}
```
那么这里是直接开辟了1024个字节，但是如果redis返回的结构超出了1024个字节，又该怎么处理呢。

**Comment by EDDYCJY** [comment]
@Devying 这里为了方便演示所以使用 1024

考虑到真实场景的话，就不能一次性读取大量值进内存了，可以使用  for + bufio.Reader + len 

通过 `br.ReadSlice('\n')` 的方式去判断+循环读取，你可以自己试试哦 

如果多人感兴趣的话，也可以专门写一篇介绍一下 🤔

----

例如：

```
for i := range r {
    r[i], err = c.readReply()
    if err != nil {
        return nil, err
    }
}

**Comment by EDDYCJY** [comment]
请问还有问题吗？？？
