### ISSUE TITLE
优雅的重启服务这块第二次kill pid之后报错

### ISSUE THREAD

**Issue by devkou** [EDDYCJY/blog#23]
优雅的重启服务这块第二次kill pid之后报错

启动之后kill第一次的pid  自动重启成功，再次kill新的pid会报错，错误如下，这个是怎么回事，怎么会找不到了呢main: no such file or directory？

Restart: Failed to launch, error: fork/exec /var/folders/27/l15hxsp56vnbhdm3mzv7534r0000gp/T/go-build220521703/b001/exe/main: no such file or directory

**Comment by devkou** [comment]
补充下 使用的 endless

**Comment by EDDYCJY** [comment]
@devkou 显然，你没有编译好二进制文件再运行？直接运行 `go run` 当然不行...

详细见文章：[Gin实践-连载七-Golang优雅重启HTTP服务.md#验证](https://github.com/EDDYCJY/blog/blob/master/golang/gin/2018-03-15-Gin%E5%AE%9E%E8%B7%B5-%E8%BF%9E%E8%BD%BD%E4%B8%83-Golang%E4%BC%98%E9%9B%85%E9%87%8D%E5%90%AFHTTP%E6%9C%8D%E5%8A%A1.md#%E9%AA%8C%E8%AF%81)
