### ISSUE TITLE
老哥, 图片看不到了,图片地址可以放到相对路径里面

### ISSUE THREAD

**Issue by xuelike** [EDDYCJY/blog#24]

**Comment by EDDYCJY** [comment]
@xuelike 你好，请问你说的是哪篇文章的图片呢？

**Comment by xuelike** [comment]
> @xuelike 你好，请问你说的是哪篇文章的图片呢？

好吧, 昨晚有可能是网络的原因 , 是图片加载不出来的,今天可以了 , 是pprof 的那篇文章, 虽然网络不好, 但是还是谢谢老哥的博文😀

**Comment by EDDYCJY** [comment]
没问题了就好，可能是因为我用的图床的问题。不客气，能帮到你就行，共勉 😄
