### ISSUE TITLE
typo test：存放用来测试喝验证Go本身的所有相关文件

### ISSUE THREAD

**Issue by qufo** [EDDYCJY/blog#25]
https://github.com/EDDYCJY/blog/blob/master/golang/gin/2018-02-16-Gin%E5%AE%9E%E8%B7%B5-%E8%BF%9E%E8%BD%BD%E4%B8%80-Golang%E4%BB%8B%E7%BB%8D%E4%B8%8E%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85.md

test：存放用来测试喝验证Go本身的所有相关文件
应为
test：存放用来测试`和`验证Go本身的所有相关文件

**Comment by EDDYCJY** [comment]
已修改错别字，感谢反馈 @qufo
