### ISSUE TITLE
Go map iteration order

### ISSUE THREAD

**Issue by ncubrian** [EDDYCJY/blog#26]
想问一下是否只是起始点是随机的呢？对于Go map {1, 2, 3}是不是不会输出1, 3, 2？

**Comment by EDDYCJY** [comment]
是的，这个主要你要看看文章里的 `runtime.mapiternext` 方法。因为起点通过随机播种后，已经决定了起始地址。后续迭代遍历就是由该方法处理的。其实答案已经在文章里了
