### ISSUE TITLE
gin实战连载-10最后的删除callback测试

### ISSUE THREAD

**Issue by NSNEVER** [EDDYCJY/blog#27]
这个测试在本地跟着教程走的时候需要修改下原来的数据库表，增加delete_on字段测试才能成功

**Comment by popo4u** [comment]
同样遇到这个问题，先watche着

**Comment by popo4u** [comment]
同遇到这个问题，稍微debug了一下没出结果，还没有深入研究grom，像Model这样一个较为底层的东西几乎被所有的model嵌入，要是手动在其他的model任务量岂不是很大。所以先关注着。

**Comment by EDDYCJY** [comment]
@NSNEVER  已修改原文中的数据库表结构，是之前写的时候没有及时更新导致的。具体以 go-gin-example 项目为基准即可。

感谢反馈。

**Comment by EDDYCJY** [comment]
@popo4u 这个字段是公共字段，因此不需要在每个 Model 手动加，只需要在 Base Model 添加就可以了

**Comment by popo4u** [comment]
嗯嗯，我是说，对于数据库的修改就没有这种嵌入关系， 需要修改所有的表。不知道有没有类似的机制，只需要在一处修改就能应用到所有的表中。

煎鱼 <notifications@github.com> 于2019年5月19日周日 下午2:48写道：
