### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by withlin** [EDDYCJY/blog#28]
>第四个成员 d
类型为 int64
大小/对齐值为 8 字节
根据规则 1，其偏移量必须为 8 的整数倍。确定偏移量为 16，因此 9-16 位为 Padding。而当前数值从第 17 位开始写入，到第 24 位。如下：axxx|bbbb|cxxx|xxxx|dddd|dddd

为啥不是：axxx|bbbb|cxxx|dddd|dddd

**Comment by Bingao-hn** [comment]
按8字节对齐，你这样不是把dddd dddd截断了
