### ISSUE TITLE
请教一下，这个程序问题在哪里？

### ISSUE THREAD

**Issue by aQuaYi** [EDDYCJY/blog#31]
https://github.com/EDDYCJY/blog/blob/master/golang/pkg/2019-05-26-Go-defer.md

···go
package main

import(
	"fmt"
)

func main(){
	fmt.Println(exchangeBack(0,1))
}

func exchangeBack(a,b int) (int,int) {
	defer func(){
		a,b = b,a 
	}()
	return b, a 
}
···

输出是 1,0
并非期望的 0,1

**Comment by aQuaYi** [comment]
想要实现 交换回来的效果，需要按照以下的方法来做。

···go
package main

import(
	"fmt"
)

func main(){
	fmt.Println(exchangeBack(0,1))
}

func exchangeBack(a,b int) (c,d int) {
	c,d = b,a  
	defer func(){
		 c,d = d,c 
	}()
	return  
}
···

**Comment by navono** [comment]
下面这个是返回命名变量。

**Comment by aQuaYi** [comment]
@navono 我记得 Go 语言传递的都是值呀！
这两个程序的差异在哪里呢？

**Comment by navono** [comment]
可以看下[这篇](https://juejin.im/post/5b9b4acde51d450e5071d51f)文章。

**Comment by aQuaYi** [comment]
@navono 谢谢，我果然遇到了坑
