### ISSUE TITLE
mysql出现无法连接

### ISSUE THREAD

**Issue by retrychx** [EDDYCJY/blog#33]
dial tcp 127.0.0.1:3306: connect: connection refused
不是在docker下面连接的，是在mac上连接mysql出的错
使用sql的驱动包可以连接，但是使用gorm无法连接，想问一下这是什么错误

**Comment by EDDYCJY** [comment]
@retrychx 上代码看看。

**Comment by retrychx** [comment]
package models

import (
	"fmt"
	"log"
	"server/pkg/setting"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var db *gorm.DB

func init() {
	var (
		err                                               error
		dbType, dbName, user, password, host, tablePrefix string
	)

	sec, err := setting.Cfg.GetSection("database")
	if err != nil {
		log.Fatal(2, "Fail to get section 'database':%v", err)
	}

	dbType = sec.Key("TYPE").String()
	dbName = sec.Key("NAME").String()
	user = sec.Key("USER").String()
	password = sec.Key("PASSWORD").String()
	host = sec.Key("HOST").String()
	tablePrefix = sec.Key("TABLE_PREFIX").String()

	fmt.Printf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local",
		user,
		password,
		host,
		dbName)

	db, err = gorm.Open(dbType, fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local",
		user,
		password,
		host,
		dbName))

	if err != nil {
		log.Println(err)
	}

	gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
		return tablePrefix + defaultTableName
	}

	db.SingularTable(true)
	db.DB().SetMaxIdleConns(10)
	db.DB().SetMaxOpenConns(100)
}

func CloseDB() {
	defer db.Close()
}


代码和你的教程基本一样，但是会出现上面的错误，使用终端可以连接mysql，使用navicat也能，所以有点搞不懂

**Comment by EDDYCJY** [comment]
@retrychx 你可以把我的 go-gin-example 的示例代码拉下来，然后配置试试看看行不行。如果不行的话，可以关注我的公众号然后加我的微信，我帮你看看。

因为你这是个人本地环境问题，非项目本身的问题，所以我先关闭了。

**Comment by oceanweave** [comment]
你好 请问解决了吗

**Comment by oceanweave** [comment]
> package models
> 
> import (
> "fmt"
> "log"
> "server/pkg/setting"
> 
> ```
> "github.com/jinzhu/gorm"
> _ "github.com/jinzhu/gorm/dialects/mysql"
> ```
> 
> )
> 
> var db *gorm.DB
> 
> func init() {
> var (
> err error
> dbType, dbName, user, password, host, tablePrefix string
> )
> 
> ```
> sec, err := setting.Cfg.GetSection("database")
> if err != nil {
> 	log.Fatal(2, "Fail to get section 'database':%v", err)
> }
> 
> dbType = sec.Key("TYPE").String()
> dbName = sec.Key("NAME").String()
> user = sec.Key("USER").String()
> password = sec.Key("PASSWORD").String()
> host = sec.Key("HOST").String()
> tablePrefix = sec.Key("TABLE_PREFIX").String()
> 
> fmt.Printf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local",
> 	user,
> 	password,
> 	host,
> 	dbName)
> 
> db, err = gorm.Open(dbType, fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local",
> 	user,
> 	password,
> 	host,
> 	dbName))
> 
> if err != nil {
> 	log.Println(err)
> }
> 
> gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
> 	return tablePrefix + defaultTableName
> }
> 
> db.SingularTable(true)
> db.DB().SetMaxIdleConns(10)
> db.DB().SetMaxOpenConns(100)
> ```
> 
> }
> 
> func CloseDB() {
> defer db.Close()
> }
> 
> 代码和你的教程基本一样，但是会出现上面的错误，使用终端可以连接mysql，使用navicat也能，所以有点搞不懂

你好，请问解决了吗？
