### ISSUE TITLE
gitbook里的trace部分图片链接挂了，可能需要更新一下

### ISSUE THREAD

**Issue by linkaka970105** [EDDYCJY/blog#37]
gitbook里的trace部分图片链接挂了，可能需要更新一下

**Comment by EDDYCJY** [comment]
@linkaka970105 我这里看到都是正常的，能给个截图来看看吗。

**Comment by linkaka970105** [comment]
> @linkaka970105 我这里看到都是正常的，能给个截图来看看吗。

我这边也可以了，刚才有一段时间是不行的，可能是这边的网络问题，刚才试了两台电脑都是出现图片显示不了的问题，现在可以啦，打扰博主啦

**Comment by EDDYCJY** [comment]
@linkaka970105 OK，学习愉快，要把我的知识转变成你的知识，有啥建议或者问题欢迎随时交流。
