### ISSUE TITLE
WaitGroup应杜绝Add和Wait方法并发执行

### ISSUE THREAD

**Issue by wxb** [EDDYCJY/blog#38]
@EDDYCJY 
hello,你好，最近在看一些你写的文章，感觉写的很好很有帮助，先感谢一下你😁

我在看
_1.6 来，控制一下 goroutine 的并发数量_
这节的:**方案一：简单 Semaphore** 时，感觉你写的
```go
func main() {
    userCount := 10
    for i := 0; i < userCount; i++ {
        go Read(i)
    }

    sema.Wait()
}

func Read(i int) {
    defer sema.Done()
    sema.Add(1)

    fmt.Printf("go func: %d, time: %d\n", i, time.Now().Unix())
    time.Sleep(time.Second)
}
```
其中 `sema.Add(1)` 和 `sema.Wait()` 放在了两个goroutine中，这种写法会在一个场景：
**Wait和Add并发执行**下存在问题，源码`WaitGroup` 的`Add` 方法中76-78行和87-89行会panic
```go
if w != 0 && delta > 0 && v == int32(delta) {
    panic("sync: WaitGroup misuse: Add called concurrently with Wait")
}
```

所以将Add和Wait 放在不同的goroutine中调用值不可靠的，我的理解提醒一下😁

**Comment by Bingao-hn** [comment]
你看的真细，虽然平时是放在同一个协程中add和wait的，但是你提出的这种panic情况还真会出现，赞

**Comment by wxb** [comment]
刚看了sync包源码，还热乎着碰巧看到了你的📚😁
