### ISSUE TITLE
panic recover 捕获的问题

### ISSUE THREAD

**Issue by alpha-baby** [EDDYCJY/blog#45]
https://github.com/developer-learning/reading-go/issues/199#issuecomment-526117181
大佬可以有空的时候看看吗，不知道这个是为什么，有空可以解答解答，感谢了。

**Comment by alpha-baby** [comment]
@EDDYCJY

**Comment by xiye518** [comment]
golang的recover只能捕获它的上一层的panic，例如

**Comment by alpha-baby** [comment]
> golang的recover只能捕获它上一层函数栈的panic，这是golang设计recover的机制，示例如下：
> 
> ```
> func test1() {
> 	// recover不能捕获当前的panic
> 	go func() {
> 		defer recover() // recover和panic在同一层级的函数栈
> 
> 		panic("panic here..")
> 	}()
> 
> 	time.Sleep(time.Second)
> 	fmt.Println("main quit...")
> }
> 
> func test2() {
> 	// recover能捕获当前的panic
> 	go func() {
> 		defer func() { // 将recover压到了下一层级的函数栈
> 			if err := recover(); err != nil {
> 				fmt.Printf("recover err: %s\n", err)
> 			}
> 		}()
> 
> 		panic("panic here..")
> 	}()
> 
> 	time.Sleep(time.Second)
> 	fmt.Println("main quit...")
> }
> ```
> 
> 大致是这样的一个设计思想，有问题欢迎讨论指正...

我觉得是这样的，recover 会和函数栈有关系，以前没有注意过这个问题。

**Comment by EDDYCJY** [comment]
@alpha-baby 可以看看文章的这一块内容：https://book.eddycjy.com/golang/panic/panic-and-recover.html#%E6%81%A2%E5%A4%8D-recover ，虽然我在文中没有明确指出这种现象，但是里面的知识点与造成你这个疑问的根本原因是有关的。

@xiye518 👍

**Comment by alpha-baby** [comment]
> @alpha-baby 可以看看文章的这一块内容：https://book.eddycjy.com/golang/panic/panic-and-recover.html#%E6%81%A2%E5%A4%8D-recover ，虽然我在文中没有明确指出这种现象，但是里面的知识点与造成你这个疑问的根本原因是有关的。
> 
> @xiye518 👍

ok 感谢，感谢
