### ISSUE TITLE
7.1 Slice 的 cap

### ISSUE THREAD

**Issue by zhangzhuanghao** [eddycjy/blog#48]
煎鱼大佬，您好

看到7.1 slice那一节

https://github.com/EDDYCJY/blog/blob/master/slice/slice.md#lencap-%E4%B8%8D%E5%90%8C
在这个地方，您说 “cap 为所引用的数组元素总个数”

我认为这样表达会造成误解
我认为cap应该从当前指向array的索引开始计算

比如说
```
arr := [10]int{}
sli := arr[1:] // cap应该从当前指向arr的索引开始计算, 这里也就是10-1=9
printSlice(sli)
```
这段代码，的执行结果为：
[0 0 0 0 0 0 0 0 0], len=9, cap=9

所以 cap 并不是 “所引用的数组元素总个数”

**Comment by eddycjy** [comment]
@zhangzhuanghao  感谢反馈，已在本地修复，等待其它 issues 均处理完后一同提交。

为了防止偏颇，已把原句修改为 “cap 为所引用的数组元素总个数（从当前指向的数组索引开始计算）”
