### ISSUE TITLE
gin 3.2节

### ISSUE THREAD

**Issue by makingBug** [eddycjy/blog#51]
以下是3.2节的部分原文：
![1](https://user-images.githubusercontent.com/41457449/67834374-39e0bb80-fb22-11e9-9312-aa3a2e94179d.PNG)
![2](https://user-images.githubusercontent.com/41457449/67834409-4f55e580-fb22-11e9-8e2e-6fcb85add943.PNG)

请问pkg下的setting目录呢？文字描述有误还是目录结构有误？望解答。

**Comment by vergilken** [comment]
That all works, at least for my test project.

**Comment by eddycjy** [comment]
目录结构贴的时候有点问题，应该为：

```
go-gin-example
├── conf
│   └── app.ini
├── go.mod
├── go.sum
├── middleware
├── models
├── pkg
├── setting
│   └── setting.go
├── routers
```

@makingBug  感谢反馈，已在本地修复，等待其它 issues 均处理完后一同提交。
