### ISSUE TITLE
关于《将Golang应用部署到Docker》有个问题

### ISSUE THREAD

**Issue by chezixin** [eddycjy/blog#53]
https://book.eddycjy.com/golang/gin/golang-docker.html

文中提到编写Dockerfile：
```
WORKDIR $GOPATH/src/github.com/EDDYCJY/go-gin-example
COPY . $GOPATH/src/github.com/EDDYCJY/go-gin-example
```

但是紧接着解释了该代码：
golang:latest 镜像为基础镜像，将工作目录设置为 $GOPATH/src/go-gin-example，
并将当前上下文目录的内容复制到 $GOPATH/src/go-gin-example 中

这里的解释和上面的代码路径不一样，请问应该如何理解呢？

**Comment by chezixin** [comment]
虽然已经知道了答案，但是不回答这个问题，这个问题就会留给下一任新来学习的同学，
作为一个有责任心的小同学，我简单解释一下：

$GOPATH/src/github.com/EDDYCJY/go-gin-example  这句话表示的就是$GOPATH/src/go-gin-example。  为什么？  因为环境不一样，作者使用的是github的地址，转换到本地文件就是$GOPATH/src/go-gin-example。

在本教程中，多处可以看到github.com/EDDYCJY/go-gin-example，表示的就是github的地址，而我们作为学习者，替换成本地路径即可。

例如：
import "github.com/EDDYCJY/go-gin-example/pkg/gredis"
变成
import "本地项目名/pkg/gredis"


你纠结过这个问题吗？  希望能帮到你。

**Comment by appleboy** [comment]
現在所有的 Go 專案幾乎都用 Module 來管理了，所以不要再討論 GOPATH 了喔，可以參考我的影片:

https://www.youtube.com/watch?v=MXjYRrZnHh0
