### ISSUE TITLE
gin响应后页面仍然无法响应

### ISSUE THREAD

**Issue by 1278651995** [eddycjy/blog#58]
在学习的Blog API's 的时候发现一个问题, 想咨询一下

**问题描述:**
 根据第三课gin的前三章所述内容, 使用postman请求Get接口, IDE的输出控制台显示200, 但页面无法响应, 
![image](https://user-images.githubusercontent.com/28895116/74501279-97a7e080-4f24-11ea-8124-4e389c0fca91.png)
![image](https://user-images.githubusercontent.com/28895116/74501285-a098b200-4f24-11ea-9f8f-4cf3754d1238.png)

**BUG出现频率**:
每次请求都会出现, 偶尔刷新几次后能正常刷出一次结果, 再次刷新就又无法响应

**尝试解决**:
尝试更换接口:  无效
将router更换为Default后, 直接router.Run()解决问题

**问题可能存在**:
	s := &http.Server{
		Addr: fmt.Sprintf(":%d", settings.HTTPPort),
		Handler: router,
		ReadTimeout: settings.ReadTimeOut,
		WriteTimeout: settings.WriteTimeOut,
		MaxHeaderBytes: 1<<20,
	}
	_ = s.ListenAndServe()
       这段代码, 但是我不知道出现在哪里,

**Comment by eddycjy** [comment]
@1278651995 你的问题很有可能出现在 ReadTimeout 或 WriteTimeout 参数没有正确的处理，可参见如下代码：

```
	ServerSetting.ReadTimeout = ServerSetting.ReadTimeout * time.Second
	ServerSetting.WriteTimeout = ServerSetting.WriteTimeout * time.Second
```

传送门：https://github.com/eddycjy/go-gin-example/blob/master/pkg/setting/setting.go#L79-L80
