### ISSUE TITLE
curl 127.0.0.1:8000总是不能正确运行

### ISSUE THREAD

**Issue by zwl1619** [EDDYCJY/blog#6]
在第2篇和第3篇中的curl 127.0.0.1:8000总是不能正确运行

[root@vagrant-dev ~]# curl 127.0.0.1:8000/test
curl: (7) Failed connect to 127.0.0.1:8000; Connection refused

哪里配置不正确吗？`app.ini`如下：
```
#debug or release
RUN_MODE = debug

[app]
PAGE_SIZE = 10
JWT_SECRET = 23347$040412

[server]
HTTP_PORT = 8000
READ_TIMEOUT = 60
WRITE_TIMEOUT = 60

[database]
TYPE = mysql
USER = root
PASSWORD = Hello1234!world
#127.0.0.1:3306
HOST = 192.168.33.3:3306
NAME = gin_blog
TABLE_PREFIX = blog_
```
编译能通过，和博客中的编译结果一样
我用的go v1.11

**Comment by EDDYCJY** [comment]
现在解决了吗？ Connection refused 的问题

显然你需要先检查本地防火墙和服务端是否正常启动等。你可以查看你服务端的机子上的 8000 端口是否正常？

**Comment by EDDYCJY** [comment]
hello?
