### ISSUE TITLE
关于“Go Modules 终极入门”文章中的一个疑问。

### ISSUE THREAD

**Issue by theoneLee** [eddycjy/blog#62]
我有一个疑问，如果本地A项目依赖本地项目B（在go mod上使用replace来替换成本地的一个相对路径），此时go mod tidy是正常的，然后本地项目B依赖本地项目C（在B的go mod上replace C项目的路径），这个时候执行go mod tidy是会有问题的。。

其实我之所以这样做，是在grpc上开发微服务的时候，proto生成的pb.go要复用的问题，后来我把所有微服务的proto都放入一个common来解决，然后所有微服务共同依赖同一个本地依赖common（都使用replace来处理该本地依赖）。

我这里姑且叫这个问题为“go mod的本地链式依赖问题”。这种问题该怎么处理呢？我的方案显然是绕过问题了。

请教一下，thx。

您的文章地址如下：
https://eddycjy.com/posts/go/go-moduels/2020-02-28-go-modules/

**Comment by eddycjy** [comment]
@theoneLee 我觉得你这个问题的本质还不是 “go mod的本地链式依赖问题” ，根本原因应当是你微服务下管理 proto 仓库的模式有问题。

因为你描述没有说的太清楚，我讲下我们的处理方式，关于不同微服务依赖多 proto 的问题，我们一般是这样子管理的：

```
grpc-demo
  | proto/
       | --- svc-a-proto
       | --- svc-b-proto
       | --- svc-c-proto
```

再配合基础工具进行 proto 的自动化生成就好了，所以不会遇到你的情况。

**Comment by theoneLee** [comment]
thx。
