### ISSUE TITLE
can't run ,help me?

### ISSUE THREAD

**Issue by kalifun** [EDDYCJY/blog#7]
$ go run main.go
# gin-blog/models
models\models.go:27:14: cannot refer to unexported name setting.config
models\models.go:27:14: undefined: setting.config

models.go
`
package models

import (
	"fmt"
	"log"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"

	"gin-blog/pkg/setting"
)

var db *gorm.DB

type Model struct {
	ID         int `gorm:"primary_key" json:"id"`
	CreatedOn  int `json:"created_on"`
	ModifiedOn int `json:"modified_on"`
}

func init() {
	var (
		err                                               error
		dbType, dbName, user, password, host, tablePrefix string
	)

	ser, err := setting.config.GetSection("database")
	if err != nil {
		log.Fatalf("Fail get selection %v", err)
	}

	dbType = ser.Key("TYPE").String()
	dbName = ser.Key("NAME").String()
	user = ser.Key("USER").String()
	password = ser.Key("PASSWORD").String()
	host = ser.Key("HOST").String()
	tablePrefix = ser.Key("TABLE_PREFIX").String()

	db, err = gorm.Open(dbType, fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local", user, password, host, dbName))
	if err != nil {
		log.Println(err)
	}
	gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
		return tablePrefix + defaultTableName
	}
	db.SingularTable(true)
	db.DB().SetMaxIdleConns(10)
	db.DB().SetMaxOpenConns(100)
}
func CloseDB() {
	defer db.Close()
}
`
setting.go
`
package setting

import (
	"time"
	"log"
	"github.com/go-ini/ini"
)

var (
	config *ini.File
	
	RunModel string

	Httpport int
	ReadTimeOut time.Duration
	WriteTimeOut time.Duration

	Pagesize int
	Jwtsecret string
)

func init() {
	var err error
	config, err = ini.Load("conf/app.ini") 
	if err != nil {
		log.Fatalf("Fail to read file: %v", err)
	}
	LoadBase()
	LoadServer()
	LoadApp()
}

func LoadBase() {
	RunModel = config.Section("").Key("RUN_MODE").MustString("debug")
}

func LoadServer() {
	ser, err := config.GetSection("server")
	if err != nil {
		log.Fatalf("Fail to get selection %v",err)
	}
	RunModel = config.Section("").Key("RUN_MODE").MustString("debug")

	Httpport = ser.Key("HTTP_PORT").MustInt(8000)
	ReadTimeOut = time.Duration(ser.Key("READ_TIMEOUT").MustInt(60)) * time.Second
	WriteTimeOut = time.Duration(ser.Key("WRITE_TIMEOUT").MustInt(60)) * time.Second
}
func LoadApp() {
	App, err := config.GetSection("app")
	if err != nil {
		log.Fatalf("Fail to get selection %v",err)
	}
	Pagesize = App.Key("PAGE_SIZE").MustInt(10)
	Jwtsecret = App.Key("JWT_SECRET").MustString("!@)*#)!@U#@*!@!)")
}
`

thank you

**Comment by EDDYCJY** [comment]
...your code is too messy. Can you organize the format and send it again?

**Comment by EDDYCJY** [comment]
hello?

**Comment by kalifun** [comment]
> hello?

sorry，my environment change，I need to debug。i will throw the problem。

**Comment by EDDYCJY** [comment]
@kalifun Please resubmit the issue after tidy up the code
