### ISSUE TITLE
大佬，关于GIN JWT验证那节有两个省略号写了什么呀

### ISSUE THREAD

**Issue by baijianruoliorz** [eddycjy/blog#76]
RT

**Comment by baijianruoliorz** [comment]
go萌新，问题蠢大佬别介意

**Comment by eddycjy** [comment]
@baijianruoliorz 你具体指的 [JWT 章节](https://eddycjy.com/posts/go/gin/2018-02-14-jwt/) 的哪里？

**Comment by baijianruoliorz** [comment]
> @baijianruoliorz 你具体指的 [JWT 章节](https://eddycjy.com/posts/go/gin/2018-02-14-jwt/) 的哪里？
> 
> 上个截图？

是gin开发博客那里整合jwt做权限来着，最后两个代码块里面加的方法打了...省略号，家长催着关电脑了，拿手机回复的，明天有机会发下截图，不好意思啊

**Comment by baijianruoliorz** [comment]
感谢大佬这么快的回复。。

**Comment by eddycjy** [comment]
@baijianruoliorz 你是指这里吗，如下图：
![image](https://user-images.githubusercontent.com/13746731/82124014-0ec46d80-97cf-11ea-94ff-25135d9fd7fb.png)

省略号的意思就是代指和之前的章节代码一样，无需变动（为了节省排版，我就用省略号代替了）。

**Comment by eddycjy** [comment]
@baijianruoliorz 没事，有问题欢迎随时沟通，好好学习 👏

**Comment by baijianruoliorz** [comment]
明白了，感谢😊

**Comment by eddycjy** [comment]
@baijianruoliorz 理解了那我关闭 issues 了，有问题再新开。
