### ISSUE TITLE
编写新增标签的路由逻辑

### ISSUE THREAD

**Issue by magic-joker** [EDDYCJY/blog#9]
https://github.com/EDDYCJY/blog/blob/master/golang/gin/2018-02-16-Gin%E5%AE%9E%E8%B7%B5-%E8%BF%9E%E8%BD%BD%E4%B8%89-%E6%90%AD%E5%BB%BABlogAPIs-02.md
logging.Info(err.Key, err.Message)这里是不是有问题,log里面没有这个。
看了你完整项目里面,是自己弄了个logging包文件。
文档更新下

**Comment by scottjeremy** [comment]
还有post请求的参数应该放在body里

**Comment by EDDYCJY** [comment]
@magic-joker 感谢反馈，已修复博文内的代码

**Comment by EDDYCJY** [comment]
@scottjeremy 另外的问题建议提新的 issue，感谢
